dev:
	poetry run python scripts/run.py

install:
	poetry run python scripts/install_db.py

uninstall:
	poetry run python scripts/uninstall_db.py

reinstall:
	poetry run python scripts/reinstall_db.py

lint:
	poetry run flake8 .
